ui: tape
tunnel:
  type: ngrok
  bind_tls: true
browsers:
  - name: chrome
    version: latest
  - name: safari
    version: 8..latest
  - name: ie
    version: 9..latest
  - name: firefox
    version: latest
  - name: opera
    version: 11..latest
  - name: ipad
    version: 8.4..latest
  - name: iphone
    version: 8.4..latest
  - name: android
    version: 5.0..latest
